feat: locate deploy key to allow shallow checkouts without fips

diff --git a/.circleci/test-deploy.yml b/.circleci/test-deploy.yml
--- a/.circleci/test-deploy.yml
+++ b/.circleci/test-deploy.yml
@@ -18,6 +18,22 @@ release-filters: &release-filters
     only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
 
 jobs:
+  # Use the default deploy key by not specifying a fingerprint.
+  checkout_deploy_key-ubuntu22-test:
+    docker:
+      - image: cimg/base:current-22.04
+    resource_class: small
+    steps:
+      - corecci/checkout_fips
+      - run:
+          name: Verify Full Checkout
+          shell: /bin/bash
+          command: |
+            if [ $(git log --oneline | wc -l) -le 1 ]; then
+              echo "Full checkout failed. Expected more than one commit."
+              exit 1
+            fi
+
   # Ubuntu 22 does not have FIPS mode enabled by default.
   checkout_fips-ubuntu22-test:
     docker:
@@ -30,7 +46,7 @@ jobs:
           name: Verify Full Checkout
           shell: /bin/bash
           command: |
-            if [ $(git log --oneline | wc -l) -lte 1 ]; then
+            if [ $(git log --oneline | wc -l) -le 1 ]; then
               echo "Full checkout failed. Expected more than one commit."
               exit 1
             fi
@@ -97,6 +113,8 @@ workflows:
   test-deploy:
     jobs:
       # Test cases for the orb
+      - checkout_deploy_key-ubuntu22-test:
+          filters: *filters
       - checkout_fips-ubuntu22-test:
           filters: *filters
       - checkout_fips_shallow-ubuntu22-test:
@@ -116,6 +134,7 @@ workflows:
           # Ensure this job requires all test jobs and the pack job.
           requires:
             - orb-tools/pack
+            - checkout_deploy_key-ubuntu22-test
             - checkout_fips-ubuntu22-test
             - checkout_fips_shallow-ubuntu22-test
             - checkout_fips_empty-ubuntu22-test
